-- Márka oszlop az italkatalógushoz (a márkarajzok hozzárendeléséhez)
-- Futtasd a Supabase SQL Editorban. Nem módosít meglévő adatot, csak új oszlopot tölt.
alter table public.ital_katalogus add column if not exists marka text;

update public.ital_katalogus set marka = case
  when nev ilike 'Hell %' then 'hell'
  when nev ilike 'Monster Energy%' then 'monster-energy'
  when nev ilike 'Absolut%' then 'absolut'
  when nev ilike 'Tatratea%' then 'tatratea'
  when nev ilike 'Royal%' then 'royal'
  when nev ilike 'Finlandia%' then 'finlandia'
  when nev ilike 'Red Bull%' then 'red-bull'
  when nev ilike 'Somersby%' then 'somersby'
  when nev ilike 'Burn %' then 'burn'
  when nev ilike 'Adrenalin%' then 'adrenalin'
  when nev ilike 'Dreher%' then 'dreher'
  when nev ilike 'Soproni%' then 'soproni'
  when nev ilike 'Jim Beam%' then 'jim-beam'
  when nev ilike 'Jack Daniels%' then 'jack-daniels'
  when nev ilike 'Jägermeister%' then 'jagermeister'
  when nev ilike 'Bomba %' then 'bomba'
  when nev ilike 'Guarana No Sleep%' then 'guarana-no-sleep'
  when nev ilike 'Jameson%' then 'jameson'
  when nev ilike 'Cîroc%' then 'ciroc'
  when nev ilike '1664%' then '1664'
  when nev ilike 'Borsodi%' then 'borsodi'
  when nev ilike 'Miller%' then 'miller'
  when nev ilike 'Ballantines%' then 'ballantines'
  when nev ilike 'Johnnie Walker%' then 'johnnie-walker'
  when nev ilike 'Euphoria%' then 'euphoria'
  when nev ilike 'Hugo Spritz%' then 'hugo-spritz'
  when nev ilike 'Bacardi%' then 'bacardi'
  when nev ilike 'Havana Club%' then 'havana-club'
  when nev ilike 'Chivas Regal%' then 'chivas-regal'
  when nev ilike 'Southern Comfort%' then 'southern-comfort'
  when nev ilike 'Beluga%' then 'beluga'
  when nev ilike 'Belvedere%' then 'belvedere'
  when nev ilike 'Grey Goose%' then 'grey-goose'
  when nev ilike 'Strongbow%' then 'strongbow'
  when nev ilike 'Arany Ászok%' then 'arany-aszok'
  when nev ilike 'Arany Fácán%' then 'arany-facan'
  when nev ilike 'Budweiser%' then 'budweiser-budvar'
  when nev ilike 'Coors%' then 'coors'
  when nev ilike 'Desperados%' then 'desperados'
  when nev ilike 'Gösser%' then 'gosser'
  when nev ilike 'Guinness%' then 'guinness'
  when nev ilike 'Heineken%' then 'heineken'
  when nev ilike 'Kőbányai%' then 'kobanyai'
  when nev ilike 'Kozel%' then 'kozel'
  when nev ilike 'Löwenbräu%' then 'lowenbrau'
  when nev ilike 'Pécsi Sör%' then 'pecsi-sor'
  when nev ilike 'Peroni%' then 'peroni'
  when nev ilike 'Staropramen%' then 'staropramen'
  when nev ilike 'Steffl%' then 'steffl'
  when nev ilike 'Stella%' then 'stella-artois'
  when nev ilike 'Figula%' then 'figula'
  when nev ilike 'Nyakas%' then 'nyakas'
  else marka
end
where marka is null;

-- Ellenőrzés: ezek maradtak márka nélkül (várhatóan a fröccsök, koktélok és az általános boros üveg)
select id, kategoria, nev from public.ital_katalogus where marka is null order by kategoria, nev;
